net.sf.jasperreports.extension.registry.factory.peecha.fonts=net.sf.jasperreports.engine.fonts.SimpleFontExtensionsRegistryFactory
net.sf.jasperreports.extension.simple.font.families.peecha=fonts/peecha-fonts.xml
